### PR TITLE
Game ported 

### PR DESCRIPTION
**Pull request by muhdmirzamz**
- Game ported. SDL 1.x functions can be used in SDL 2.0.1. I just changed a little here and there
- Timer functions are not ported as I'm not familiar with it.
- Crashes on colour assignment in square class
- Managed to run on mac with Uint64, BUT blitting in game.cpp crashes
- Released some dynamically allocated pointers

I'm sorry I couldn't fix the bugs and fully port it

### CODE REVIEW

**Comment by leonn** [comment]
So let's  work together to fix everything , i'll install  OSX86 Snow Leopard on virtual box  and fork your repository  and then i'll try to make it work.

**Comment by muhdmirzamz** [comment]
Ok, I will continue working on it!

**Comment by leonn** [comment]
nice work man  o/
this week i'll test and do the merge

**Comment by leonn** [comment]
nice work man o/

**Pull request merged**
